# Generated by Django 3.0.6 on 2020-05-24 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient'), ('hr', 'hr'), ('receptionist', 'receptionist')], default='admin', max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(default='', max_length=10)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('activate', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
