# Generated by Django 3.0.6 on 2020-05-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
