# Generated by Django 3.0.6 on 2020-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
